### PR TITLE
Hotfix and improvement

### PR DESCRIPTION
**Pull request by refaim**
- Fix serious bug with that prevents plugin's work on Linux
- Launch "Show symbols" in background

### CODE REVIEW

**Comment by pitkali** [comment]
It is not only Linux that is affected. On Mac I kept getting TypeError in the console when trying to find references. It works again after updating to the head commit of this request.

Not the master of the sources repository though, as there Find all references does not work, claiming there are no references.

**Comment by refaim** [comment]
Oh, boy. I really should write some unit tests. Thanks for report, I fixed it.

**Comment by pitkali** [comment]
I can confirm it now works fine :)

**Comment by koko1000ban** [comment]
thanks. i merged.

**Pull request merged**
